### ISSUE TITLE
Empty access_token

### ISSUE THREAD

**Issue by danifr** [jorgecarleitao/ipython-oidc-client#3]
Hi Jorge,

sorry to bother you with this but I couldn't make your plugin work.
I am running the jupyter notebook in a container from the Docker image you provided.

This is my notebook code:
```
from ipython_oidc_client import authenticate

access_configuration = {
    'authority': 'https://keycloakXXXX.server/auth/realms/test/.well-known/openid-configuration',
    'client_id': 'jupyter-test',
    'response_type': 'id_token',
    'scope': 'openid',
}

token = {}
authenticate(access_configuration, token)  # this changes token (see note in README.md)
```
I recorded a screencast to illustrate my problem better (hope the quality is OK, I needed to convert it to GIF)

![screencast](https://user-images.githubusercontent.com/7135482/89168340-05040800-d57d-11ea-8106-aba6e7210c0f.gif)

Do you know what might be happening? Thanks a lot

**Comment by jorgecarleitao** [comment]
Almost! You just need to re-run the cell after the authentication is completed, so that the js sends the token to the kernel.

So:

* run cell 1
* authenticate
* redirection
* run cell 1

**Comment by danifr** [comment]
I might be terribly mistaken, but I think this is what I am doing.

After login in and being redirected, I rerun cell number 1 and I get:
`token = {'access_token': {}}`

Inspecting my browser requests I can see a 403.
![image](https://user-images.githubusercontent.com/7135482/89230181-1ed83600-d5e3-11ea-9891-6e9f57138ea0.png)

Do I need a special config for the keycloak client?
Thanks a lot!

**Comment by jorgecarleitao** [comment]
Sorry, I misunderstood your screen cast, and thanks for the patience.

I think that the issue is that you are requesting an `token_id`, not `token`, with `'response_type': 'id_token'`.

This plugin currently only works with `token/access_token` as its purpose is for the kernel to be authorized to access an API. `id_token` is used for authentication, which is usually insufficient to access a resource: the resource does not know who can access it because it delegated that to the identity provider (through scopes).

If you intended to use `token`, just change your response type to `token`:

<img width="1077" alt="Screenshot 2020-08-04 at 07 10 23" src="https://user-images.githubusercontent.com/2772607/89255290-a6dd3080-d621-11ea-94e5-5238809d04ce.png">

If you intended to use `id_token`, I made a small modification to the code [on branch id_token](https://github.com/jorgecarleitao/ipython-oidc-client/tree/id_token) that should support your use-case. I am not sure it is useful for the kernel to have an id token, though.

To validate it, I deployed keycloak on docker, and was able to get the id token. I used the following commands:

```
docker run -p 8080:8080 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin quay.io/keycloak/keycloak:11.0.0

docker build -f Dockerfile.dev -t t . && docker run -p 8888:8888 -v $(pwd):/project --rm -it t
```

Cell in notebook:

```
from ipython_oidc_client import authenticate


access_configuration = {
    'authority': 'http://localhost:8080/auth/realms/test/.well-known/openid-configuration',
    'client_id': 'test-jupyter',
    'response_type': 'id_token',
    'scope': 'openid',
}
# valid variables available here: https://github.com/IdentityModel/oidc-client-js/wiki#usermanager

token = {}
authenticate(access_configuration, token)  # this changes token (see note in README.md)
```

and configured a user and client as described [here](https://www.keycloak.org/getting-started/getting-started-docker) and I enabled `Implicit Flow Enabled` on the application, as the `response_type` above has no `code`.

Here is the result:

<img width="1072" alt="Screenshot 2020-08-04 at 05 55 37" src="https://user-images.githubusercontent.com/2772607/89251394-33362600-d617-11ea-9f00-e67067adab80.png">

**Comment by jorgecarleitao** [comment]
However, I did find that the current code did not work with the `response_type: 'code'`.

I just released a fix for that on 0.1.3.

The docker image is likely cached, so you will need to change to `RUN pip install ipython_oidc_client==0.1.3` for it to use the latest.

**Comment by danifr** [comment]
Thanks a lot for that explanation!! Very very detailed! I made it work :) :tada: 

Do you know if your extension also works in jupyterlab? I tried modifying your Dockerfile a bit but I am getting an error:
```
Exception opening new comm vendors~main.aee10a0dbdadee16025a.js:2:2370867
    _handleCommOpen http://127.0.0.1:9999/static/lab/vendors~main.aee10a0dbdadee16025a.js:2
```
Thanks a lot for your valuable help!!!!!

**Comment by jorgecarleitao** [comment]
Perfect, I am glad it worked!

Gitlab -> I haven't tried it yet. Sounds feasible though.

**Comment by danifr** [comment]
Great, we can close this one! Looking forward to see [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/) support in the future!
Maybe I can help with part of the code/tests if you someone to give you a hand!
